config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  get 'books' => 'books#index'
  post 'books' => 'books#create'
  get 'books/:id' => 'books#show', as: 'book'
  get 'books/:id/edit' => 'books#edit', as: 'edit_book'
  patch 'books/:id' => 'books#update', as: 'update_book'
  delete 'books/:id' => 'books#destroy', as: 'destroy_book'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
 

  def index
    @books = Book.all
    @book = Book.new
  end


  def create
    book = Book.new(book_params)
    book.save
    redirect_to book_path(book.id)
  end


  def show
    @book = Book.find(params[:id])

  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
  end

  def destroy
    @book = Book.find(params[:id])
  end


  private
  def book_params
    params.require(:book).permit(:title,:body)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/index.html.erb
<h1>Books</h1>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.body %></td>
        <td><%= link_to "Show", book_path(book.id) %></td>
        <td><%= link_to "Edit", edit_book_path(book.id) %></td>
       
      </tr> 
    <% end %>
  </tbody>
</table>

<h2>New book</h2>
<form class="new_book">
  <%= form_with model:@book, url:books_path, local:true do |f| %>
   <div class="field">
     <h4>Title</h4>
     <%= f.text_field :title %>
   </div>
   <div class="field">
     <h4>Body</h4>
     <%= f.text_area :body %>
   </div>
   <div class="action">
     <%= f.submit "Create Book" %>
   </div>
  <% end %>
</form>

app/views/books/show.html.erb
<p><strong>Title:</strong><%= @book.title %></p>
<p><strong>Body:</strong><%= @book.body %></p>
<p>Edit</p>|<p>Back</p>

app/views/homes/top.html.erb
<h1>ようこそ<strong>Bookers</strong>へ！</h1>

<p><strong>Bookers</strong>では、さまざまな書籍に関するあなたの意見や</p>

<p>印象を共有し交換することができます</p>

<p><%= link_to "start", books_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blue</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>